/**
 * Генератор кода Tampermonkey-скрипта.
 * Вызывается из AdminPanel для отображения скрипта пользователю.
 */
export function getUserscriptCode() {
  return [
    "// ==UserScript==",
    "// @name         RomeoPro Forum Crawler",
    "// @namespace    https://github.com/your-username/romeoprotracker",
    "// @version      2.1",
    "// @description  Crawls RomeoPro marathon thread and sends data to tracker",
    "// @match        https://forum.gipsyteam.ru/*",
    "// @run-at       document-idle",
    "// @grant        GM_setClipboard",
    "// ==/UserScript==",
    "(function () {",
    "  var TOPIC = '181676';",
    "  var FLAG  = 'rp_crawling';",
    "  var DATA  = 'rp_posts';",
    "  var PAGE  = 'rp_page';",
    "",
    "  if (!location.href.includes('viewtopic=' + TOPIC)) return;",
    "  var params = new URLSearchParams(location.search);",
    "  var mode   = params.get('rp_mode') || sessionStorage.getItem(FLAG);",
    "  if (!mode) return;",
    "  sessionStorage.setItem(FLAG, mode);",
    "",
    "  // Overlay",
    "  var ov = document.createElement('div');",
    "  ov.id = 'rp-ov';",
    "  ov.style.cssText = 'position:fixed;bottom:20px;right:20px;z-index:999999;background:#061208;border:2px solid #15803d;border-radius:12px;padding:14px 18px;font-family:sans-serif;font-size:13px;color:#d1fae5;min-width:260px;box-shadow:0 8px 32px rgba(0,0,0,.8);';",
    "  ov.innerHTML = '<div style=\"font-weight:700;color:#4ade80;margin-bottom:6px;\">RomeoPro Crawler</div><div id=\"rp-st\">Инициализация...</div><div style=\"height:5px;background:#0f2016;border-radius:3px;margin-top:8px;\"><div id=\"rp-bar\" style=\"height:100%;width:0%;background:linear-gradient(90deg,#15803d,#4ade80);transition:width .5s;\"></div></div><div id=\"rp-inf\" style=\"font-size:11px;color:#374151;margin-top:4px;\"></div>';",
    "  document.body.appendChild(ov);",
    "",
    "  function setSt(s,i){var e=document.getElementById('rp-st'),f=document.getElementById('rp-inf');if(e)e.textContent=s;if(f&&i)f.textContent=i;}",
    "  function setBar(p){var b=document.getElementById('rp-bar');if(b)b.style.width=p+'%';}",
    "",
    "  function extractPosts() {",
    "    var posts = [];",
    "    document.querySelectorAll('a[href*=\"autocom=postvote\"][href*=\"value=1\"]').forEach(function(vl) {",
    "      try {",
    "        var pm = vl.href.match(/pid=(\\d+)/); if (!pm) return;",
    "        var pid = pm[1];",
    "        var li = vl; while (li && li.tagName !== 'LI') li = li.parentElement; if (!li) return;",
    "        var author=null,rep=null,postCount=null,yearsOnSite=null;",
    "        li.querySelectorAll('a[href*=\"/profile/\"]').forEach(function(a) {",
    "          var t=a.textContent.trim(),n=parseInt(t.replace(/[,\\s]/g,''));",
    "          if(!author&&t&&isNaN(n)&&t!=='\\u041F\\u0440\\u043E\\u0444\\u0438\\u043B\\u044C')author=t;",
    "          if(!isNaN(n)){if(!a.href.includes('/forumposts')&&rep===null)rep=n;else if(a.href.includes('/forumposts')&&postCount===null)postCount=n;}",
    "        });",
    "        var vc=vl.nextElementSibling;",
    "        var rating=vc?(parseInt(vc.textContent)||0):0;",
    "        var ltxt=li.textContent;",
    "        var tm=ltxt.match(/(\\d{1,2}\\.\\d{2}\\.\\d{2,4},\\s*\\d{2}:\\d{2})/g);",
    "        var ts=tm?tm[tm.length-1]:null;",
    "        var ym=ltxt.match(/(\\d+)\\s*\\u043B\\u0435\\u0442\\s*\\u043D\\u0430\\s*\\u0441\\u0430\\u0439\\u0442\\u0435/);",
    "        if(ym)yearsOnSite=parseInt(ym[1]);",
    "        var avEl=li.querySelector('img[src*=\"Avatar\"]');",
    "        var avatarUrl=avEl?avEl.src:null;",
    "        var images=[];",
    "        li.querySelectorAll('img').forEach(function(img){if(img.src&&!img.src.includes('Avatar')&&!img.src.includes('/img/')&&img.naturalWidth>50)images.push(img.src);});",
    "        var clone=li.cloneNode(true);",
    "        ['a[href*=profile]','a[href*=autocom]','a[href*=findpost]','img'].forEach(function(s){clone.querySelectorAll(s).forEach(function(e){e.remove();});});",
    "        var body=clone.textContent.replace(/\\u041E\\u0442\\u0432\\u0435\\u0442\\u0438\\u0442\\u044C[\\s\\S]*/,'').split('\\n').map(function(l){return l.trim();}).filter(Boolean).join('\\n').trim();",
    "        var isRomeopro=(author||'').toLowerCase()==='romeopro';",
    "        var brMentioned=null;",
    "        if(isRomeopro){var bm=body.match(/\\$(\\d[\\d,]*)\\s*k?\\b/i);if(bm){var v=parseFloat(bm[1].replace(/,/g,''));if(/\\$[\\d,]+k/i.test(bm[0]))v*=1000;if(v>500&&v<5000000)brMentioned=v;}}",
    "        posts.push({id:pid,author:author,authorReputation:rep,postCount:postCount,yearsOnSite:yearsOnSite,text:body,rating:rating,timestamp:ts,isRomeopro:isRomeopro,brMentioned:brMentioned,avatarUrl:avatarUrl,images:images,postUrl:'https://forum.gipsyteam.ru/index.php?viewtopic=181676&view=findpost&p='+pid});",
    "      } catch(e) {}",
    "    });",
    "    return posts;",
    "  }",
    "",
    "  function merge(a,b){var m={};(a||[]).forEach(function(p){if(p&&p.id)m[String(p.id)]=p;});(b||[]).forEach(function(p){if(p&&p.id)m[String(p.id)]=p;});return Object.values(m);}",
    "",
    "  function nextUrl(){",
    "    var cur=parseInt(new URLSearchParams(location.search).get('st')||'0');",
    "    var best=null;",
    "    document.querySelectorAll('a[href*=\"viewtopic=181676\"]').forEach(function(a){var m=a.href.match(/st=(\\d+)/);if(m){var n=parseInt(m[1]);if(n>cur&&(best===null||n<best))best=n;}});",
    "    if(best===null)return null;",
    "    var url='https://forum.gipsyteam.ru/index.php?viewtopic=181676&st='+best;",
    "    if(mode==='author')url+='&filter=author';",
    "    return url;",
    "  }",
    "",
    "  function extractBrData(ap){",
    "    return ap.filter(function(p){return p.brMentioned;}).map(function(p){",
    "      var dm=(p.text||'').match(/[\\u0414\\u0434]\\u0435\\u043D\\u044C\\s*(\\d+)|[Dd]ay\\s*(\\d+)/);",
    "      var day=dm?parseInt(dm[1]||dm[2]):null;",
    "      return{day:day,totalBr:p.brMentioned,profit:p.brMentioned-10000,label:day?('\\u0414\\u0435\\u043D\\u044C '+day):(p.timestamp||'?'),postUrl:p.postUrl,postText:(p.text||'').slice(0,120)};",
    "    }).filter(function(d){return d.day!==null;}).sort(function(a,b){return a.day-b.day;});",
    "  }",
    "",
    "  function ping(ev,extra){",
    "    if(!window.opener)return false;",
    "    try{var m={type:'romeoproAgent',event:ev};Object.keys(extra||{}).forEach(function(k){m[k]=extra[k];});window.opener.postMessage(m,'*');return true;}catch(e){return false;}",
    "  }",
    "",
    "  function copyResult(str){",
    "    try{if(typeof GM_setClipboard!=='undefined'){GM_setClipboard(str);return true;}}catch(e){}",
    "    try{navigator.clipboard.writeText(str);return true;}catch(e){}",
    "    try{var ta=document.createElement('textarea');ta.value=str;ta.style.position='fixed';ta.style.top='-9999px';document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);return true;}catch(e){return false;}",
    "  }",
    "",
    "  // Main",
    "  var page=extractPosts();",
    "  var prev=[];try{prev=JSON.parse(sessionStorage.getItem(DATA)||'[]');}catch(e){}",
    "  var all=merge(prev,page);",
    "  sessionStorage.setItem(DATA,JSON.stringify(all));",
    "  var pc=(parseInt(sessionStorage.getItem(PAGE)||'0'))+1;",
    "  sessionStorage.setItem(PAGE,String(pc));",
    "  var est=mode==='author'?4:mode==='recent'?10:181;",
    "  setBar(Math.min(95,Math.round((pc/est)*100)));",
    "  setSt('\\u0421\\u0442\\u0440. '+pc+' | '+all.length+' \\u043F\\u043E\\u0441\\u0442\\u043E\\u0432');",
    "  ping('progress',{pageCount:pc,totalPosts:all.length,pageUrl:location.href});",
    "  var next=nextUrl();",
    "  if(next){setTimeout(function(){location.href=next;},900);}",
    "  else{",
    "    var ap=all.filter(function(p){return p.isRomeopro;});",
    "    var bd=extractBrData(ap);",
    "    var result={type:'rp_crawler_result',posts:all,brData:bd,pageCount:pc};",
    "    var str=JSON.stringify(result);",
    "    var pmOk=ping('done',{posts:all,brData:bd,pageCount:pc});",
    "    copyResult(str);",
    "    sessionStorage.removeItem(FLAG);sessionStorage.removeItem(DATA);sessionStorage.removeItem(PAGE);",
    "    var oe=document.getElementById('rp-ov');",
    "    if(oe){oe.style.background='#052e16';oe.style.borderColor='#4ade80';",
    "      oe.innerHTML='<div style=\"font-weight:800;color:#4ade80;font-size:15px;margin-bottom:8px;\">\\u2705 \\u0413\\u043E\\u0442\\u043E\\u0432\\u043E!</div>'+",
    "        '<div style=\"color:#d1fae5;margin-bottom:6px;\">'+all.length+' \\u043F\\u043E\\u0441\\u0442\\u043E\\u0432, '+pc+' \\u0441\\u0442\\u0440\\u0430\\u043D\\u0438\\u0446</div>'+",
    "        (pmOk?'<div style=\"font-size:12px;color:#6b7280;\">\\u0414\\u0430\\u043D\\u043D\\u044B\\u0435 \\u043E\\u0442\\u043F\\u0440\\u0430\\u0432\\u043B\\u0435\\u043D\\u044B \\u0430\\u0432\\u0442\\u043E\\u043C\\u0430\\u0442\\u0438\\u0447\\u0435\\u0441\\u043A\\u0438 \\u2714</div>':"+
    "        '<div style=\"background:#0a2010;border:1px solid #15803d;border-radius:8px;padding:10px;margin-top:8px;font-size:12px;color:#86efac;\">\\u0414\\u0430\\u043D\\u043D\\u044B\\u0435 \\u0441\\u043A\\u043E\\u043F\\u0438\\u0440\\u043E\\u0432\\u0430\\u043D\\u044B!<br>\\u0412\\u0435\\u0440\\u043D\\u0438\\u0442\\u0435\\u0441\\u044C \\u0432 \\u0442\\u0440\\u0435\\u043A\\u0435\\u0440 \\u2192 \\u0410\\u0434\\u043C\\u0438\\u043D \\u2192 \\u00AB\\u0412\\u0441\\u0442\\u0430\\u0432\\u0438\\u0442\\u044C \\u0440\\u0435\\u0437\\u0443\\u043B\\u044C\\u0442\\u0430\\u0442\\u044B\\u00BB</div>');",
    "    }",
    "    if(pmOk)setTimeout(function(){window.close();},3000);",
    "  }",
    "})();",
  ].join('\n');
}
